[package]
name = "rust-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]   # important for generating a DLL on Windows

[dependencies]
uniffi = "0.28"

[build-dependencies]
uniffi_build = "0.28"